import type { Metadata } from "next";

import { Geist, Geist_Mono, Roboto } from "next/font/google";
import Sidebar from "../components/sidebar";
import Header from "../components/header";
import "./globals.css";
import Notifications from "@/components/notifications";
import HeaderFeatures from "@/components/headerFeatures";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // pick the weights you need
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Evolve Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex bg-stone-200" suppressHydrationWarning>
        <Sidebar />
        <div className="w-full relative">
          <HeaderFeatures />

          <div className="pt-16 ml-60">{children}</div>
        </div>
      </body>
    </html>
  );
}
